version: "3.9"

services:
  web:
    build: .
    container_name: fastapi_app
    ports:
      - "8000:8000"
    environment:
      - BIGQUERY_CREDENTIALS_PATH=./credentials/news-collect-and-store-22be09d2b3f9.json

    volumes:
      - .:/app
    command: bash -c "python3 main.py && uvicorn api.main:app --host 0.0.0.0 --port 8000 --reload"